# SQLite version 3.x
#  gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['DB_HOST'] || '127.0.0.1' %>
  username: <%= ENV['DB_USERNAME'] || "root" %>
  password: <%= ENV['DB_PASSWORD'] %>
  reconnection: true
  port: <%= ENV['DB_PORT'] || '3306' %>
development:
  <<: *default
  pool: 5
  database: helloapp_development
test:
  <<: *default
  database: helloapp_test
production:
  <<: *default
  database: helloapp_production

